dashboard/urls.py
__author__ = 'xavier'
from django.conf.urls import url
from . import views

urlpatterns = [
    #url(r'^$', views.index, name='index'),


    url(r'^$', views.ClientFormView.as_view(), name='client-form'),

    url(r'^results/(?P<client_id>.+)$', views.results, name='results')
]

joole/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('dashboard.urls', namespace="dashboard")),
    url(r'^admin/', admin.site.urls),
]

dashboard/models.py
from django.db import models


class Conso_eur(models.Model):
    client_id = models.IntegerField()
    janvier = models.FloatField()
    fevrier = models.FloatField()
    mars = models.FloatField()
    avril = models.FloatField()
    mai = models.FloatField()
    juin = models.FloatField()
    juillet = models.FloatField()
    aout = models.FloatField()
    septembre = models.FloatField()
    octobre = models.FloatField()
    novembre = models.FloatField()
    decembre = models.FloatField()
    year = models.IntegerField()

    def __str__(self):
        return str(self.client_id)


class Conso_watt(models.Model):
    client_id = models.IntegerField()
    janvier = models.FloatField()
    fevrier = models.FloatField()
    mars = models.FloatField()
    avril = models.FloatField()
    mai = models.FloatField()
    juin = models.FloatField()
    juillet = models.FloatField()
    aout = models.FloatField()
    septembre = models.FloatField()
    octobre = models.FloatField()
    novembre = models.FloatField()
    decembre = models.FloatField()
    year = models.IntegerField()

    def __str__(self):
        return str(self.client_id)

dashboard/forms.py
from django import forms

class ClientForm(forms.Form):
    client = forms.CharField(
        label='Tapez votre numero de client', max_length=200
    )

dashboard/views.py
from django.shortcuts import render, redirect
from django.views.generic import View

from .forms import ClientForm
from .models import Conso_eur, Conso_watt


class ClientFormView(View):
    def get(self, request):
        return render(request, 'dashboard/accueil.html')

    def post(self, request):
        form = ClientForm(request.POST)

        if form.is_valid():
            client_id = form.cleaned_data['client']
            return redirect('dashboard:results', client_id=client_id)

def results(request, client_id):
    conso_euro = []
    conso_watt = []
    annual_costs = [0, 0]
    is_elec_heating = True
    dysfunction_detected = False

    conso_excessive = []

    """Recherche d'une consommation excessive en plein hiver"""
    for cw in Conso_watt.objects.filter(janvier__in=(range(900,1800)), id=client_id):
        conso_excessive.append(cw)

    if len(conso_excessive) == 0:
        is_elec_heating = False

    """Récupération de toutes les consommations en euro du client de l'année 2016"""
    ce16 = Conso_eur.objects.get(id=client_id, year=2016)

    total_2016 = ce16.janvier + ce16.fevrier + ce16.mars + ce16.avril + ce16.mai + ce16.juin + ce16.juillet + ce16.aout + ce16.septembre + ce16.octobre + ce16.novembre + ce16.decembre

    """Récupération de toutes les consommations en euro du client de l'année 2017"""
    for elt in Conso_eur.objects.filter(year=2017):
        if int(elt.client_id) == int(client_id):
            ce17 = elt

    total_2017 = ce17.janvier + ce17.fevrier + ce17.mars + ce17.avril + ce17.mai + ce17.juin + ce17.juillet + ce17.aout + ce17.septembre + ce17.octobre + ce17.novembre + ce17.decembre

    """Restriction à 2 chiffres après la virgule maximum"""
    total_2016 = float("%.2f" % total_2016)
    total_2017 = float("%.2f" % total_2017)

    annual_costs = [total_2016, total_2017]

    """Comparaison des totaux des deux années pour y trouver une grande différence ou non"""
    if is_very_different(total_2016, total_2017):
        dysfunction_detected = True

    """Récupération des données pour le graphique"""
    for cwatt in Conso_watt.objects.filter(year=2017):
        if int(cwatt.client_id) == int(client_id):
            conso_watt=[cwatt.janvier, cwatt.fevrier, cwatt.mars, cwatt.avril, cwatt.mai, cwatt.juin, cwatt.juillet, cwatt.aout, cwatt.septembre, cwatt.octobre, cwatt.novembre, cwatt.decembre]

    context = {
        "conso_euro": conso_euro,
        "conso_watt": conso_watt,
        "annual_costs": annual_costs,
        "is_elec_heating": is_elec_heating,
        "dysfunction_detected": dysfunction_detected,
    }
    return render(request, 'dashboard/results.html', context)

def is_very_different(val_2016, val_2017):

    if (val_2016 - val_2017 >= 400) or (val_2017 - val_2016 >= 400):
        return True
    else:
        return False

dashboard/templates/dashboard/accueil.html
<!DOCTYPE html>
<html lang="fr">

{% load static %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Joole</title>

    <link href="/static/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">
    <link href="/static/dist/css/timeline.css" rel="stylesheet">
    <link href="/static/dist/css/sb-admin-2.css" rel="stylesheet">
    <link href="/static/bower_components/morrisjs/morris.css" rel="stylesheet">
    <link href="/static/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
</head>

<body style="background-color: white">
    <div class="container" >
        <div class="row" style="text-align: center; margin-top:15rem; margin-bottom: 3rem">
            <img src="/static/dist/img/logo-medium.png" >
        </div>
        <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group input-group form-group-lg">
                 <input id="id_client" maxlength="20" name="client" type="text" class="form-control" id="id_client" required placeholder="Entrez votre numéro de client">
                    <span class="input-group-btn">
                        <button class="btn btn-primary btn-lg" type="submit"><i class="fa fa-bolt"></i></button>
                    </span>
            </div>
        </form>
        </div>
    </div>
    </div>
</body>
</html>

dashboard/templates/dashboard/results.html
{% extends 'dashboard/results_base.html' %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'dashboard/css/results.css' %}" media="all"/>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Mon tableau de bord énergie</h1>
    </div>
</div>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
  google.charts.load('current', {'packages':['corechart']});
  google.charts.setOnLoadCallback(drawChart);

  function drawChart() {
    var data = google.visualization.arrayToDataTable([
      ['Mois', 'Watt/mois'],
      ['Janvier',  {{conso_watt.0}}],
      ['Février',  {{conso_watt.1}}],
      ['Mars',  {{conso_watt.2}}],
      ['Avril',  {{conso_watt.3}}],
      ['Mai',  {{conso_watt.4}}],
      ['Juin',  {{conso_watt.5}}],
      ['Juillet',  {{conso_watt.6}}],
      ['Août',  {{conso_watt.7}}],
      ['Septembre',  {{conso_watt.8}}],
      ['Octobre',  {{conso_watt.9}}],
      ['Novembre',  {{conso_watt.10}}],
      ['Décembre',  {{conso_watt.11}}]
    ]);

    var options = {
      title: 'Votre consommation de 2017',
      curveType: 'function',
      legend: { position: 'top' }
    };

    var chart = new google.visualization.LineChart(document.getElementById('curve_chart'));

    chart.draw(data, options);
  }
</script>
<body>
  <div id="curve_chart"></div>

  <ul class="annual_costs">
    <li>Vos dépenses en 2016 : {{ annual_costs.0 }} €</li>
    <li>Vos dépenses en 2017 : {{ annual_costs.1 }} €</li>
  </ul>

  {% if is_elec_heating %}
    <p class="is_elec_heating">Vous possédez un chauffage électrique</p>
  {% else %}
    <p class="is_elec_heating">Vous ne possédez pas de chauffage électrique</p>
  {% endif %}

  {% if dysfunction_detected %}
    <p id="yes_dysfunction_detected" class="dysfunction">Dysfonctionnement détecté</p>
  {% else %}
    <p id="no_dysfunction_detected" class="dysfunction">Aucun dysfonctionnement détecté</p>
  {% endif %}

</body>

{% block script %}
    <script src="{% static 'dashboard/js/results.js' %}"></script>
{% endblock %}

{% endblock %}

dashboard/templates/dashboard/results_base.html
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Joole</title>

    <link href="/static/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">
    <link href="/static/dist/css/timeline.css" rel="stylesheet">
    <link href="/static/dist/css/sb-admin-2.css" rel="stylesheet">
    <link href="/static/bower_components/morrisjs/morris.css" rel="stylesheet">
    <link href="/static/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    {% block style %}
    {% endblock %}
</head>

<body>

    <div id="wrapper">
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html"><img src="/static/dist/img/logo-xs.png"></a>
            </div>

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> Mon profil</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Mes informations de conso</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Se déconnecter</a>
                        </li>
                    </ul>
                </li>
            </ul>

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">

                        <li>
                            <a href="index.html"><i class="fa fa-dashboard fa-fw"></i> Mon tableau de bord</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-tasks fa-fw"></i> Mes missions<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="flot.html">Missions possibles</a>
                                </li>
                                <li>
                                    <a href="morris.html">Historique des missions</a>
                                </li>
                            </ul>
                        </li>
                         <li>
                            <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Ma consommation<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="flot.html">Mois par mois</a>
                                </li>
                                <li>
                                    <a href="morris.html">Par appareils</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="tables.html"><i class="fa fa-users fa-fw"></i> Me comparer</a>
                        </li>
                        <li>
                            <a href="forms.html"><i class="fa fa-bell fa-fw"></i> Notification</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-comments fa-fw"></i> Nous contacter<span class="fa arrow"></span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <div id="page-wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </div>

    <script src="/static/bower_components/jquery/dist/jquery.min.js"></script>
    <script src="/static/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="/static/bower_components/metisMenu/dist/metisMenu.min.js"></script>
    <script src="/static/bower_components/raphael/raphael-min.js"></script>
    <script src="/static/bower_components/morrisjs/morris.min.js"></script>
    <script src="/static/dist/js/sb-admin-2.js"></script>
</body>

{% block script %}
{% endblock %}

</html>